sudo: required

services:
- docker

env:
  global:
    -secure "gJ/6mAfJNW3WltqseX1RAjC4o9BL9a8twa+LIxGMHW4aqqThmN3fhDRcGTHXZ6TlajmcJBdv0Fn6QKgz7o8fPklgNH3uH8z1zHqcbTXHtLbmeKW0tisgcdhmak9Lcvltx8CrQ3/KHThcVvJoHfolPhEvOc6EHE9KLu6DGS2TsKtKlpk7ocmW8b45vtc+4S9FKXnRx522MItVVYIEGUJ2FqbywD79A0zqrHnVhBmYQmLeCOYQMPOa5p22jwLZvJrxE0Lip1/nZ+jEvwu52BXFQekxH+Qj5+Jtn9kuD592vJwxdj9lBiqh+qgGTUE8HC+/qTlFvTSbw1UAwQwZU+sMw0pjHDm/ibq1adqZqi3UVv2k/2naaUYH9jFJ8Av6bltvY6jf/GRXGkudO2S9OhmLB3oHNGKeiZ1gKSS2SMTYal38aPz11q53ZVVFQGSooFD/wkBC45vaeUZbNaeO+V4nkMuuWnS4UNDKyo8c85CiS61ZdW+Al+Rqwz0GKXsqqqEYdk5u0cpobKLu9S46jbHg5V3mOlwma8S7wDqB+FPjIMd7Xcod/nlniuNmNHTurrJwHowL4pjdaYPYXC1BlKltZFYNxxyqpDiXFgXMNVTO48CPF97vZQH1IYvixTOCmEX5ass0zvkTj+7sAELcB9AN5uoPiUMCNxjjcEen39Q94SQ=" #DOCKER_USERNAME
    -secure "SZwkhgtwEWTbVbq1hs00sfdI2WpbR29lwaeUHZSfE0Kg6kMyuDGS2GrNxQYFAimduwYLhya5clWAdzz+PDLMOJv8oWcCj5g9pUlr6omOP26IzQOZXGRQ/8COceV7FJwgq6uQ5FhL25weTXatHFio0nBKmhr3oX4ncjXSjWrLxUbNe7Ff6h9JfOugryS277CRWuXiul48n7FRveuZtS3xs6BHo8NDGfTCrgav4jA4M2UzDzLVx+2CJGUFibOLR1UNT4ZDr7YGUXVZLVH/M1BdAYLHd6/M5vlPUDyjESYIz69i6lnJJeQAsY5WsVhgcJbR3/0G1PWI7oimUmJJWtT7IliwMwlwXTSvWFB1YiaVOyV5uqcl2q9WHbmt5tfY/5E/qLPOR8Q8znWX8R1f/7K4Rx+CLFeN6BpLnaMexQ7v2/lWAbLwo60IRb048RWBdlNOgO4vdWKAfUW+sDxc6tT+jGAPtG3jycTzNJOJMVhBHpcAHIYX6JTQLVl6ol8HWcVDIRLMrGZtAxnEIpee7phTGsSn3ckv4z0RlfEUZm57SvD5vrbLqkBHTnc4hYr7N1E0YV9ABfzx6/uRY0cgNj/5NtjKhxJE5tBq9pcrWuWcr54ySj4lADz4TbXCs8v9M8d7Jjrsww3wcQx2dxK/Lh8eKr7Ep6EoGM7TZBO29AHDFdU=" #DOCKER_PASSWORD
    -secure "ShIr7j18R877c9ocG96Uyvon7gb68npKBeCVwP5OTJa9l04x1pAJiBBPa+diPPA1sh9HoK8cK3JfdQjHfft5Cj9JCfFtWvHbHJioxujZyb9cfAQjkmL/dMRjwQYEnm69UxZKIB/zMUOvwgh5pFw1sWnOCXNPaLWDpxdV3nFeGv4Y1+dgT9O5wXRJrtvsyaP08KuBGYd5lEYP4o/qb2B6utf16ZavSI1fNWxPZ73l3rqvgnWu8jKMRWdPoSOv+EGpMb76P3X8MrSw1qvWkfb8LZDobEQ8s2Ni2aX2MykovquNXioo4InMEZRyvXGeT2+ZPJOot3RgnWgMTH2yoa0tgsobHstPcR/jZEPbREmAF0z2KDP0OyQnOF6gxRqDyY3dCQG8iGbIbsGbu1BnRfP3P0NNusiAhxjST7CSXAJDqtPWDfk3nM57q3YWmk1aBKi5vy3WKK2qCRwirGtoFKq/wy312teMXcOFoTsJsoMWeNkoxJiSibEoz1icQzNSyL81JF8SFjo8gKaLkhemeoWVmiN+NbhlIMlKVlOgziWKMgd+UtkSKNU6Mvz5SY+vizv0wa//vaWqVwoAHBGWX8X/dqe2uc4PvZThq4z8UKqunpGYDJ01A7A+V/NTO8aclhNy3rSdOWvEYTatrU9MLWLtgT7ycGEq1B7ycaTE+IvmSlI=" #DOCKER_EMAIL

before_install:
  - docker build -t drish96/tweebotd .

script:
  - docker images drish96/tweebotd

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push drish96/tweebotd;
    fi