sudo: required

services:
  - docker

before_install:
  - docker build -t drish96/tweebotd .

script:
  - docker images drish96/tweebotd

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push drish96/tweebotd;
    fi