version: '2'

services:
  mongo:
    image: mongo
    ports:
      - "27017"

  redis:
    image: redis
    ports:
      - "6379"

  ml-classification-server:
    image: drish96/ml-classification-server
    ports:
      - "5000"

  ui:
    image: drish96/tweebotd
    ports:
      - "8085:8085"
    links:
      - mongo
      - redis
      - ml-classification-server
    depends_on:
      - mongo
      - redis
      - ml-classification-server
    environment:
      - "CONSUMER_KEY=${CONSUMER_KEY}"
      - "CONSUMER_SECRET=${CONSUMER_SECRET}"
      - "ACCESS_TOKEN=${ACCESS_TOKEN}"
      - "ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}"
      - "SESSION_SECRET=${SESSION_SECRET}"
      - "MONGODB_URL=${MONGODB_URL}"
      - "REDIS_PORT=${REDIS_PORT}"
      - "REDIS_HOSTNAME=${REDIS_HOSTNAME}"
      - "CALLBACK_URL=${CALLBACK_URL}"
      - "LAMBDA_URL=${LAMBDA_URL}"
      - "NODE_ENV=${NODE_ENV}"
